ltslam:

  sessions_dir: "/home/twq/data_bag/LT_mapper/data_parsed/" 

  central_sess_name: "01" # should be same as the directory name of that session
  query_sess_name: "02" # should be same as the directory name of that session
  
  save_directory: "/home/twq/data_bag/LT_mapper/data_ltslam/0102/" 

  is_display_debug_msgs: false

  loopFitnessScoreThreshold: 0.7

  kNumSCLoopsUpperBound: 1000 # if you use an enough number, use all the detected loops 
  kNumRSLoopsUpperBound: 0 # if you use an enough number, use all the detected loops 

  numberOfCores: 8 # currently hard-coded in the utility.cpp

